# https://cloud.google.com/run/docs/continuous-deployment#continuous
# https://cloud.google.com/cloud-build/docs/configuring-builds/substitute-variable-values

steps:
  # build the container image
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/github.com/alperenbelgic/ci-cd-sample', '.']
  # push the container image to Container Registry
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ci-cd-sample']
  # Deploy container image to Cloud Run
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['beta', 'run', 'deploy', 'ci-cd-sample', '--image', 'gcr.io/$PROJECT_ID/ci-cd-sample', '--region', 'europe-west1','--platform', 'managed', '--quiet']
images:
- gcr.io/$PROJECT_ID/ci-cd-sample